source "https://rubygems.org"

ruby "3.0.6"

gem "rails", "~> 7.1.3"

gem "pg", "~> 1.5"

gem "puma", ">= 6.0"

# Para RabbitMQ (como consumidor)
gem 'bunny'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mswin mswin64 mingw x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

group :development, :test do
  gem 'rspec-rails'
  gem 'database_cleaner-active_record'
  gem 'webmock'
  gem "debug", platforms: %i[ mri mswin mswin64 mingw x64_mingw ]
  gem 'shoulda-matchers'
  gem 'factory_bot_rails'
  gem 'faker'
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end
